---
- name: Install default programs
  apt: "name={{ item }} state=present"
  with_items:
    - git
    - vim
    - emacs25
    - fasd
    - python3-pip
    - python-pip

- include: dotfiles.yml
- include: emacs.yml
